package exception;

public interface ExceptionMassages {
	String ILLIAGAL_ARGUMENT_EXCEPTION = "ILLIAGAL_ARGUMENT_EXCEPTION";
	String ARITHMETIC_EXCEPTION ="ARITHMETIC_EXCEPTION";
	String ILLIAGAL_ACCESS_EXCEPTION= "ILLIAGAL_ACCESS_EXCEPTION";
	String MY_EXCEPTION= "MY_EXCEPTION";
}
